AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bb-oem-lambda-app

  Apollo GraphQL running as a lambda function
  
Globals:
  Function:
    Timeout: 30

Resources:
  GQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 30
      MemorySize: 4096
      Layers:
        - !Sub "arn:aws:lambda:us-west-2:764866452798:layer:chrome-aws-lambda:22" 
      Events:
        GQLApi:
          Type: Api
          Properties:
            Path: /gql
            Method: any

Outputs:
  GQLApi:
    Description: "API Gateway endpoint URL for Prod stage for GraphQL function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/gql/"
  GQLFunction:
    Description: "GQL Lambda Function ARN"
    Value: !GetAtt GQLFunction.Arn
  GQLFunctionIamRole:
    Description: "Implicit IAM Role created for GraphQL function"
    Value: !GetAtt GQLFunctionRole.Arn
